// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTmAHEo0hBclGK3dR7s5VmTTKwAbd7PRA',
    appId: '1:1029545254538:web:b7c8ff568c3990bf3dd773',
    messagingSenderId: '1029545254538',
    projectId: 'chatting-app-b55d9',
    authDomain: 'chatting-app-b55d9.firebaseapp.com',
    storageBucket: 'chatting-app-b55d9.appspot.com',
    measurementId: 'G-FRWT3EWK6S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBOvHADfAM12mp104ROvT_tzdplTkz4zA',
    appId: '1:1029545254538:android:d8f5aea47af002573dd773',
    messagingSenderId: '1029545254538',
    projectId: 'chatting-app-b55d9',
    storageBucket: 'chatting-app-b55d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAlSCSinfr28PCJ0rNzV8rFsUl16NHGKs',
    appId: '1:1029545254538:ios:1472fa982765b6a03dd773',
    messagingSenderId: '1029545254538',
    projectId: 'chatting-app-b55d9',
    storageBucket: 'chatting-app-b55d9.appspot.com',
    iosClientId: '1029545254538-42ki8mu26g5dh5dariafmkgj3nlihucd.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAlSCSinfr28PCJ0rNzV8rFsUl16NHGKs',
    appId: '1:1029545254538:ios:8d8120ec1e5d56303dd773',
    messagingSenderId: '1029545254538',
    projectId: 'chatting-app-b55d9',
    storageBucket: 'chatting-app-b55d9.appspot.com',
    iosClientId: '1029545254538-6v4lehd8mqu59uj996qhq79c1h2h4op5.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattingApp.RunnerTests',
  );
}
